# 📁 .github/workflows/code-review.yml

name: Code Review GPT

on:
  pull_request:
    types: [opened, synchronize]  # Triggers on new or updated PRs

jobs:
  run_code_review:
    runs-on: ubuntu-latest

    steps:
      # ✅ This checks out the repository code into the GitHub runner
      - uses: actions/checkout@v4

      # ✅ This runs the GPT-based code review action
      - name: Run Code Review GPT
        uses: mattzcarey/code-review-gpt@v0.8.0
        with:
          GITHUB_TOKEN: ${{ github.token }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: "gpt-4o"
          REVIEW_LANGUAGE: "English"
