name: CI with SonarQube and Mailgun

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=code-review \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=$SONAR_TOKEN || echo "SONAR_FAILED=true" >> $GITHUB_ENV

      - name: Always Notify via Mailgun (on both success and failure)
        env:
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        run: |
          curl -s --user "api:$MAILGUN_API_KEY" \
            https://api.mailgun.net/v3/sandbox0dc4f69b76bb445480873a1165edcb68.mailgun.org/messages \
            -F from="SonarQube Alert <postmaster@sandbox0dc4f69b76bb445480873a1165edcb68.mailgun.org>" \
            -F to=yerramchattyshivasaiteja2003@gmail.com \
            -F subject="SonarQube Analysis Status" \
            -F text="The SonarQube analysis for the code-review project has completed successfully. Check the dashboard for details."
